//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cheese {
            get {
                object obj = ResourceManager.GetObject("cheese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cheese1 {
            get {
                object obj = ResourceManager.GetObject("cheese1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cheese2 {
            get {
                object obj = ResourceManager.GetObject("cheese2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;keyNodes&quot;: {
        ///    &quot;zelda&quot;: &quot;zelda.player.inv&quot;,
        ///    &quot;metroid&quot;: &quot;metroid.player.inv.equipment&quot;,
        ///    &quot;zflags&quot;: &quot;zelda.flags&quot;,
        ///    &quot;mstats&quot;: &quot;metroid.player.inv&quot;,
        ///    &quot;zstats&quot;: &quot;zelda.player.stat&quot;
        ///},
        ///&quot;associations&quot;: {
        ///    &quot;wand&quot;: &quot;zelda.rod&quot;,
        ///    &quot;sword&quot;: &quot;zelda.sword&quot;,
        ///    &quot;boomerang&quot;: &quot;zelda.boom&quot;,
        ///    &quot;recorder&quot;: &quot;zelda.recorder&quot;,
        ///    &quot;bow&quot;: &quot;zelda.bow&quot;,
        ///    &quot;raft&quot;: &quot;zelda.raft&quot;,
        ///    &quot;candle&quot;: &quot;zelda.candle&quot;,
        ///    &quot;ladder&quot;: &quot;zelda.ladder&quot;,
        ///    &quot;book&quot;: &quot;zelda.book&quot;,
        ///    &quot;arrow&quot;: &quot;zelda.arro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string z1m1Associations {
            get {
                return ResourceManager.GetString("z1m1Associations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;files&quot;: {
        ///    },
        ///    &quot;layouts&quot;: {
        ///        &quot;zelda&quot;: {
        ///            &quot;backgrounds&quot;: [
        ///                &quot;z1m1-0.png&quot;,
        ///                &quot;z1m1-1.png&quot;,
        ///                &quot;z1m1-2.png&quot;,
        ///                &quot;z1m1-3.png&quot;
        ///            ],
        ///            &quot;indicators&quot;: {
        ///                &quot;tri1&quot;: {
        ///                    &quot;x&quot;: 16,
        ///                    &quot;y&quot;: 16,
        ///                    &quot;w&quot;: 32,
        ///                    &quot;h&quot;: 33,
        ///                    &quot;max&quot;: 2
        ///                },
        ///               &quot;tri2&quot;: {
        ///                    &quot;x&quot;: 4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string z1m1Layout {
            get {
                return ResourceManager.GetString("z1m1Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;files&quot;:{&quot;!/packedfile0&quot;:&quot;iVBORw0KGgoAAAANSUhEUgAAAiAAAAHgCAMAAACrVyYHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAMAUExURQAAAAEBAQICAgMDAwQEBAUFBQYGBgcHBwgICAkJCQoKCgsLCwwMDA0NDQ4ODg8PDxAQEBERERISEhMTExQUFBUVFRYWFhcXFxgYGBkZGRoaGhsbGxwcHB0dHR4eHh8fHyAgICEhISIiIiMjIyQkJCUlJSYmJicnJygoKCkpKSoqKisrKywsLC0tLS8vLzAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string z1m1PackedLayout {
            get {
                return ResourceManager.GetString("z1m1PackedLayout", resourceCulture);
            }
        }
    }
}
